package cierrelote

// const ERROR_NUMBER_CARD = "el númer de tarjeta no es valido"
// const ERROR_DATE_CARD = "la fecha de vencimiento de la tarjeta es invalido"
// const ERROR_HOLDER_NAME = "nombre no valido"
// const ERROR_SITE_TRANSACTION_ID = "id de ttansacción es incorrecto "
// const ERROR_TOKEN_PAGO = "token de pago no valido"
// const ERROR_BIN = "el número de bien es incorrecto"
// const ERROR_AMOUNT = "el monto ingresado no es valido"
// const ERROR_CURRENCY = "la moneda seleccionada no es valida"
// const ERROR_INSTALLMENTS = "el valor ingresado es incorrecto"
// const ERROR_PAYMENT_TYPE = "el tipo de pago es incorrecto"
// const ERROR_ESTABLISHMENT_NAME = "el número de carcter es superior a 25 o no posee caracter no permitidos"
// const ERROR_NRO_DOC = "el numero de documento ingresado no es valido"
// const ERROR_ESTRUCTURA_INCORRECTA = "los datos recibidos son incorrectos"
// const ERRR_TIPO_PAGO = "tipo de pago no valido"
// const ERRR_INFO_PAGO = "el número de pago no existe o es incorrecto"
// const ERROR_NUMBER_PAGE_SIZE = "page size debe ser un valor mayor a 0"
// const ERROR_FECHA = "formato de fecha no valido, formato valido es (AAAA-MM-DD)"
// const ERROR_EXTERNAL_ID = "external id no es valida"
// const ERROR_PETICION_ANULACION_DEVOLUCION = "error al intentar anular el pago"

// const ERROR_OPEN_ARCHIVO = "error al intentar abrir archivo"
// const ERROR_CREATE_ARCHIVO = "error al intentar crear archivo"
// const ERROR_READ_ARCHIVO = "error al intentar Leer archivos"
// const ERROR_REMOVER_ARCHIVO = "error al intentar eliminar archivo"
const (
	ERROR_AL_CREAR_NOTIFICACION                  = "error al intentar guardar notificaciones"
	ERROR_AL_CREAR_LOG                           = "error al intentar crear un log"
	ERROR_MOVER_ARCHIVO                          = "error al intentar mover archivo"
	ERROR_REMOVER_ARCHIVO                        = "error al intentar eliminar archivo"
	ERROR_GENERAL_ARCHIVO                        = "no existen archivo de cierre de lote en el directorio"
	ERROR_LEER_CARACTER                          = "error al leer strings"
	ERROR_CONVERTIR_ENTERO                       = "error al convertir a númenro entero"
	ERROR_CONVERTIR_DECIMAL                      = "error al convertir a númenro decimal"
	ERROR_CONVERTIR_FECHA                        = "error al convertir fecha"
	ERROR_PAGO_ESTADO                            = "error al solicitar lista de estados de pago"
	ERROR_PAGO_ESTADO_VACIO                      = "error lista de estados pago se encuentra vacía"
	ERROR_LEER_DIRECTORIO                        = "error al intentar leer los archivos del directorio "
	ERROR_DIRECTORIO_VACIO                       = "el directorio esta vacío, no existe cierre de lote"
	ERROR_OBTENER_ID_CHANNELARANCEL              = "error al intentar obtener arancel DE prisma"
	ERROR_OBTENER_CL_PRISMA                      = "error al intentar obtener cierre de lotes de prisma"
	ERROR_OBTENER_MOVIMIENTOS_BANCO              = "error al intentar obtener movimientos de banco"
	ERROR_PARSER_FECHA                           = "error al intentar parsear fecha, formato de fecha no valido"
	ERROR_ACTUALIZAR_CL_PRISMA                   = "error al intentar actualizar cierre de lotes conciliados"
	ERROR_CONCILIACION                           = "no existen registros para conciliar"
	ERROR_OBTENER_CONFIGURACION                  = "error al intentar obtener configuracion de los periodos de acreditación"
	ERROR_NO_EXISTE_CONFIGURACION                = "no existe configuración cargada para los periodo de acreditación"
	ERROR_CONVERTIR_VALOR                        = "error al intentar convertir valor"
	ERROR_RECORRER_ARCHIVOS                      = "error al recorrer el archivo:"
	ERROR_CONSULTAR_ARANCELES                    = "error al obtener los aranceles, no se puede crear la lista de cierre de lote."
	ERROR_MEDIO_PAGO_NO_EXISTE                   = "no se encontraron medios de pago para el cierre de lote."
	ERROR_LISTA_CIERRE_LOTE_NO_CREADO            = "error al crear lista de cieere de lotes"
	ERROR_OBTENER_CONFIGURACION_IMPUESTO_ARANCEL = "error al obtener impuesto aplicado sobre arancel"
	ERROR_REGISTRO_EN_DB                         = "error al agregar registros en la base de datos "
	ERROR_FORMATO_REGISTRO                       = "error en el formato del archivo, registro 02 o 04 estan mal construidos"
	ERROR_FORMATO_REGISTRO_02                    = "error al convertir el registro (02)"
	ERROR_FORMATO_REGISTRO_04                    = "error al convertir el registro (04)"
	ERROR_FORMATO_REGISTRO_MOVIMIENTO            = "error en el formato del archivo, registro totales o detalle estan mal construidos"
	ERROR_FORMATO_REGISTRO_MIVIMIENTO_DETALLE    = "error al convertir el registro detalle"
	ERROR_FORMATO_REGISTRO_MIVIMIENTO_TOTALES    = "error al convertir el registro totales"
	ERROR_CONSULTAR_MOVIMIENTOS_MX               = "al consultar los registros totales y detalle del archivo movimiento mx"
	RESULT_CONSULTAR_MOVIMIENTOS_MX              = "no se encontraron movimientos mx registrados"
	ERROR_REFERENCIAS_MOVIMIENTOS                = "no existen referencias de estableciminetos"

	ERROR_CONSULTAR_TABLA_CODIGOS_RECHAZOS    = "al consultar las tabla codígos rechazo"
	RESULT_CONSULTAR_TABLA_CODIGOS_RECHAZOS   = "la tabla codígos rechazo no se encuentra cargada"
	ERROR_CONSULTAR_TABLA_VISA_CONTRACARGO    = "al consultar las tabla visa contracargo"
	RESULT_CONSULTAR_TABLA_VISA_CONTRACARGO   = "la tabla visa contracargo no se encuentra cargada"
	ERROR_CONSULTAR_TABLA_MOTIVOS_AJUSTE      = "al consultar las tabla motivo ajuste"
	RESULT_CONSULTAR_TABLA_MOTIVOS_AJUSTE     = "la tabla motivo ajuste no se encuentra cargada"
	ERROR_CONSULTAR_TABLA_OPERACIONES         = "al consultar las tabla operaciones"
	RESULT_CONSULTAR_TABLA_OPERACIONES        = "la tabla operaciones no se encuentra cargada"
	ERROR_CONSULTAR_TABLA_MASTER_CONTRACARGO  = "al consultar las tabla master contracargo"
	RESULT_CONSULTAR_TABLA_MASTER_CONTRACARGO = "la tabla master contracargo no se encuentra cargada"
	ERROR_CONSULTAR_PAGOS_PX                  = "al consultar los registros totales y detalle del archivo pagos px"
	RESULT_CONSULTAR_PAGOS_PX                 = "no se encontraron pagos px registrados"

	ERROR_FORMATO_REGISTRO_RP                  = "error en el formato del archivo"
	ERROR_FORMATO_REGISTRO_RP_TRAILER_DETALLES = "error en la validacion detalles y trailer, verificar archivo"
	ERROR_CONVERT_REGISTRO                     = "error al convertir el registro, header o trailer"
	ERROR_CONSULTAR_IMPUESTOS                  = "error al intentar obtener los impuesto"
	ERROR_LISTA_IMPUESTOS_VACION               = "error la listas de impuestaos se encuentra vacia"
	ERROR_CONSULTAR_CIERRE_LOTE                = "al consultar los cierres de lotes"
	ERROR_OBTENER_LISTA_CIERRE_LOTE            = "no se ha podido obtener informacion de cierre lote"
	ERROR_OBTENER_LISTA_PAGOS_INTENTOS         = "no se ha podido obtener informacion de pagos intentos"
	ERROR_LISTA_CIERRE_LOTE_VACIA              = "lista cierre lote se encuetra vacia"
	ERROR_CONSULTAR_PRISMA_MOVIMIENTOS         = "al consultar los movimientos generados por plataforma prisma"
	ERROR_OBTENER_LISTA_PRISMA_MOVIMIENTOS     = "no se ha podido obtener informacion de prisma movimientos"
	ERROR_LISTA_PRISMA_MOVIMIENTOS_VACIA       = "lista prisma movimientos se encuetra vacia"
	ERROR_CONCILIACION_CL_MOVIMIENTOS          = "no se pudo realizar la conciliacion cierre lote con movimiento"
	ERROR_CONSULTAR_PRISMA_PAGOS               = "al consultar los pagos generados por plataforma prisma"
	ERROR_OBTENER_LISTA_PRISMA_PAGOS           = "no se ha podido obtener informacion de prisma pagos"
	ERROR_LISTA_PRISMA_PAGOS_VACIA             = "lista prisma pagos se encuetra vacia"

	ERROR_CALCULAR_COMISION_RAPIPAGO = "error al calcular comision rapipago"

	ERROR_OBTENER_NOMBRE_ARCHIVOS = "error al obtener el nombre del archivo"
	ERROR_ARCHIVO_REPETIDO        = "error al subir el archivo, el archivo ya existe"
	ERROR_CHANNEL_NO_EXISTE       = "channel no existe"
	// errores de herramienta cierre de lote
	RESULTADO_NO_ENCONTRADO  = "repositorio: no se encontraron resultados para la busqueda"
	ERROR_CARGAR_CIERRE_LOTE = "repositorio: no se pudo cargar el cierre de lote desde la base de datos"
	ERROR_GET_CIERRE_LOTE    = "repositorio: no se puedieron obtener los registros de cierre de lote"
	ERROR_CARGAR_TOTAL_FILAS = "no se pudo cargar el total de filas de la consulta"
)
