package administracionfake

import (
	"time"

	"github.com/Corrientes-Telecomunicaciones/api_go_pasarela_background/pkg/entities"
	"gorm.io/gorm"
)

var listaPagos []entities.Pago = []entities.Pago{
	{
		Model:             gorm.Model{ID: 7},
		PagostipoID:       1,
		Description:       "Pago de impuesto al sello",
		PagoestadosID:     7,
		FirstDueDate:      time.Now(), //time.Parse("2006-01-02", "2021-06-10"),
		FirstTotal:        66051,
		SecondDueDate:     time.Now().Add(15 * 24 * time.Hour), //time.Parse("2006-01-02", " 2021-07-10"),
		SecondTotal:       68055,
		PayerName:         "juan pericles",
		PayerEmail:        "fernando.castro@telco.com.ar",
		ExternalReference: "155571",
		Uuid:              "3b1c9d8cd6966w4",
		PdfUrl:            "No existe el PDF",
		PagoIntentos: []entities.Pagointento{
			{
				Model:                gorm.Model{ID: 6},
				PagosID:              7,
				MediopagosID:         1,
				InstallmentdetailsID: 1,
				ExternalID:           "10676472",
				PaidAt:               time.Now(),
				ReportAt:             time.Now(),
				IsAvailable:          false,
				Amount:               66051,
				StateComment:         "approved",
				Barcode:              "",
				BarcodeUrl:           "",
				AvailableAt:          time.Now(),
				RevertedAt:           time.Now(),
				HolderName:           "Ignacio Fernandez",
				HolderEmail:          "Ignacio Fernandez",
				TicketNumber:         "",
				AuthorizationCode:    "152523",
				CardLastFourDigits:   "4905",
			},
		},
		PagoEstados: entities.Pagoestado{
			Model:  gorm.Model{ID: 4},
			Estado: "Paid",
			Final:  false,
		},
		PagosTipo: entities.Pagotipo{
			Model: gorm.Model{
				ID: 1,
			},
			CuentasID:       1,
			Pagotipo:        "sellos",
			BackUrlSuccess:  "http://www.google.com",
			BackUrlPending:  "http://www.infobae.com",
			BackUrlRejected: "http://clarin.com.ar",
			// IncludedChannels:     "credit, debit, offline, debin",
			// IncludedInstallments: "1,3,6,12",
		},
	},
	{
		Model:             gorm.Model{ID: 8},
		PagostipoID:       1,
		Description:       "Pago de impuesto al sello",
		PagoestadosID:     7,
		FirstDueDate:      time.Now(),
		FirstTotal:        76051,
		SecondDueDate:     time.Now().Add(15 * 24 * time.Hour),
		SecondTotal:       78055,
		PayerName:         "Nacho Fernandez",
		PayerEmail:        "fernando.castro@telco.com.ar",
		ExternalReference: "155571",
		Uuid:              "ce86bbf2d468aw4",
		PdfUrl:            "No existe el PDF",
		PagoIntentos: []entities.Pagointento{
			{
				Model:                gorm.Model{ID: 8},
				PagosID:              8,
				MediopagosID:         1,
				InstallmentdetailsID: 1,
				ExternalID:           "10676500",
				PaidAt:               time.Now(),
				ReportAt:             time.Now(),
				IsAvailable:          false,
				Amount:               76051,
				StateComment:         "approved",
				Barcode:              "",
				BarcodeUrl:           "",
				AvailableAt:          time.Now(),
				RevertedAt:           time.Now(),
				HolderName:           "Castro",
				HolderEmail:          "Castro",
				TicketNumber:         "",
				AuthorizationCode:    "153031",
				CardLastFourDigits:   "4905",
			},
		},
		PagoEstados: entities.Pagoestado{
			Model:  gorm.Model{ID: 4},
			Estado: "Paid",
			Final:  false,
		},
		PagosTipo: entities.Pagotipo{
			Model: gorm.Model{
				ID: 1,
			},
			CuentasID:       1,
			Pagotipo:        "sellos",
			BackUrlSuccess:  "http://www.google.com",
			BackUrlPending:  "http://www.infobae.com",
			BackUrlRejected: "http://clarin.com.ar",
			// IncludedChannels:     "credit, debit, offline, debin",
			// IncludedInstallments: "1,3,6,12",
		},
	},
	{
		Model:             gorm.Model{ID: 11},
		PagostipoID:       1,
		Description:       "Pago de impuesto al sello",
		PagoestadosID:     7,
		FirstDueDate:      time.Now(),
		FirstTotal:        76051,
		SecondDueDate:     time.Now().Add(15 * 24 * time.Hour),
		SecondTotal:       78055,
		PayerName:         "Nicolás de la Cruz",
		PayerEmail:        "fernando.castro@telco.com.ar",
		ExternalReference: "155572",
		Uuid:              "d820cfb2db8d8w4",
		PdfUrl:            "No existe el PDF",
		PagoIntentos: []entities.Pagointento{
			{
				Model:                gorm.Model{ID: 5},
				PagosID:              11,
				MediopagosID:         1,
				InstallmentdetailsID: 1,
				ExternalID:           "10676452",
				PaidAt:               time.Now(),
				ReportAt:             time.Now(),
				IsAvailable:          false,
				Amount:               76051,
				StateComment:         "approved",
				Barcode:              "",
				BarcodeUrl:           "",
				AvailableAt:          time.Now(),
				RevertedAt:           time.Now(),
				HolderName:           "Ignacio Fernandez",
				HolderEmail:          "Ignacio Fernandez",
				TicketNumber:         "",
				AuthorizationCode:    "152414",
				CardLastFourDigits:   "4905",
			},
		},
		PagoEstados: entities.Pagoestado{
			Model:  gorm.Model{ID: 4},
			Estado: "Paid",
			Final:  false,
		},
		PagosTipo: entities.Pagotipo{
			Model: gorm.Model{
				ID: 1,
			},
			CuentasID:       1,
			Pagotipo:        "sellos",
			BackUrlSuccess:  "http://www.google.com",
			BackUrlPending:  "http://www.infobae.com",
			BackUrlRejected: "http://clarin.com.ar",
			// IncludedChannels:     "credit, debit, offline, debin",
			// IncludedInstallments: "1,3,6,12",
		},
	},
	{
		Model:             gorm.Model{ID: 12},
		PagostipoID:       1,
		Description:       "Pago de impuesto al sello",
		PagoestadosID:     3,
		FirstDueDate:      time.Now(),
		FirstTotal:        76051,
		SecondDueDate:     time.Now().Add(15 * 24 * time.Hour),
		SecondTotal:       78055,
		PayerName:         "Nicolás de la Cruz",
		PayerEmail:        "fernando.castro@telco.com.ar",
		ExternalReference: "155572",
		Uuid:              "77c86bb9d8cf5w4",
		PdfUrl:            "No existe el PDF",
		PagoIntentos: []entities.Pagointento{
			{
				Model:                gorm.Model{ID: 3},
				PagosID:              12,
				MediopagosID:         1,
				InstallmentdetailsID: 1,
				ExternalID:           "10676296",
				PaidAt:               time.Now(),
				ReportAt:             time.Now(),
				IsAvailable:          false,
				Amount:               76051,
				StateComment:         "approved",
				Barcode:              "",
				BarcodeUrl:           "",
				AvailableAt:          time.Now(),
				RevertedAt:           time.Now(),
				HolderName:           "De la Cruz N",
				HolderEmail:          "De la Cruz N",
				TicketNumber:         "",
				AuthorizationCode:    "123",
				CardLastFourDigits:   "4905",
			},
		},
		PagoEstados: entities.Pagoestado{
			Model:  gorm.Model{ID: 4},
			Estado: "Paid",
			Final:  false,
		},
		PagosTipo: entities.Pagotipo{
			Model: gorm.Model{
				ID: 1,
			},
			CuentasID:       1,
			Pagotipo:        "sellos",
			BackUrlSuccess:  "http://www.google.com",
			BackUrlPending:  "http://www.infobae.com",
			BackUrlRejected: "http://clarin.com.ar",
			// IncludedChannels:     "credit, debit, offline, debin",
			// IncludedInstallments: "1,3,6,12",
		},
	},
}

/*
	{
    "cierre lote": [
        {
            "ID": 34,
            "CreatedAt": "2021-06-25T15:01:06Z",
            "UpdatedAt": "2021-06-25T15:01:06Z",
            "DeletedAt": null,
            "pagos_uuid": "3b1c9d8cd6966w4",
            "pagoestadoexternos_id": 7,
            "tipo_operacion": "C",
            "monto": 680.55,
            "fecha_cierre": "2021-06-16T00:00:00Z",
            "externallote_id": 789,
            "nombrearchivolote": "lotetelco_060621.001.txt"
        },
        {
            "ID": 35,
            "CreatedAt": "2021-06-25T15:01:06Z",
            "UpdatedAt": "2021-06-25T15:01:06Z",
            "DeletedAt": null,
            "pagos_uuid": "ce86bbf2d468aw4",
            "pagoestadoexternos_id": 7,
            "tipo_operacion": "C",
            "monto": 760.51,
            "fecha_cierre": "2021-06-16T00:00:00Z",
            "externallote_id": 789,
            "nombrearchivolote": "lotetelco_060621.001.txt"
        },
        {
            "ID": 36,
            "CreatedAt": "2021-06-25T15:01:06Z",
            "UpdatedAt": "2021-06-25T15:01:06Z",
            "DeletedAt": null,
            "pagos_uuid": "d820cfb2db8d8w4",
            "pagoestadoexternos_id": 7,
            "tipo_operacion": "C",
            "monto": 760.51,
            "fecha_cierre": "2021-06-16T00:00:00Z",
            "externallote_id": 789,
            "nombrearchivolote": "lotetelco_060621.001.txt"
        },
        {
            "ID": 37,
            "CreatedAt": "2021-06-25T15:01:06Z",
            "UpdatedAt": "2021-06-25T15:01:06Z",
            "DeletedAt": null,
            "pagos_uuid": "77c86bb9d8cf5w4",
            "pagoestadoexternos_id": 3,
            "tipo_operacion": "A",
            "monto": 760.51,
            "fecha_cierre": "2021-06-16T00:00:00Z",
            "externallote_id": 789,
            "nombrearchivolote": "lotetelco_060621.001.txt"
        }
    ],



    PAGOS
    "lista de pagos": [
        {
            "ID": 7,
            "CreatedAt": "2021-05-28T12:45:45Z",
            "UpdatedAt": "2021-06-07T11:29:50Z",
            "DeletedAt": null,
            "pagostipo_id": 1,
            "pagoestados_id": 7,
            "description": "Pago de impuesto al sello",
            "first_due_date": "2021-06-10T00:00:00Z",
            "first_total": 660.51,
            "second_due_date": "2021-07-10T00:00:00Z",
            "second_total": 680.55,
            "payer_name": "Enzo Fernandez",
            "payer_email": "fernando.castro@telco.com.ar",
            "external_reference": "155571",
            "metadata": "",
            "uuid": "3b1c9d8cd6966w4",
            "pdf_url": "No existe el PDF",


            "pagotipo": {
                "ID": 1,
                "CreatedAt": "2021-05-14T12:49:49Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "cuentas_id": 1,
                "pagotipo": "sellos",
                "back_url_success": "http://www.google.com",
                "back_url_pending": "http://www.infobae.com",
                "back_url_rejected": "http://clarin.com.ar",
                "included_channels": "credit, debit, offline, debin",
                "included_installments": "1,3,6,12",
                "cuenta": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "clientes_id": 0,
                    "cuenta": "",
                    "cbu": "",
                    "cvu": "",
                    "apikey": "",
                    "pagotipos": null,
                    "cuentacomisiones": null
                }
            },
            "pagoestados": {
                "ID": 4,
                "CreatedAt": "2021-06-03T12:39:44Z",
                "UpdatedAt": "2021-06-03T12:39:44Z",
                "DeletedAt": null,
                "estado": "Paid",
                "final": false
            },
			/////////////////////////////////////
            "pago_intentos": [
                {
                    "ID": 6,
                    "CreatedAt": "2021-06-03T18:25:25Z",
                    "UpdatedAt": "2021-06-30T15:06:41Z",
                    "DeletedAt": null,
                    "pagos_id": 7,
                    "mediopagos_id": 1,
                    "installmentdetails_id": 1,
                    "external_id": "10676472",
                    "paid_at": "2021-06-03T15:25:00Z",
                    "report_at": "2021-06-03T18:25:25Z",
                    "is_available": false,
                    "amount": 660.51,
                    "state_comment": "approved",
                    "barcode": "",
                    "barcode_url": "",
                    "available_at": "2021-06-16T00:00:00Z",
                    "reverted_at": "0001-01-01T00:00:00Z",
                    "holder_name": "Ignacio Fernandez",
                    "holder_email": "Ignacio Fernandez",
                    "ticket_number": "",
                    "authorization_code": "152523",
                    "card_last_four_digits": "4905",
                    "mediopago": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "channels_id": 0,
                        "adquirientes_id": 0,
                        "installments_id": 0,
                        "mediopago": "",
                        "external_id": "",
                        "longitud_pan": 0,
                        "longitud_cvv": 0,
                        "installmentdetail": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "descripcion": "",
                            "issuer": "",
                            "vigencia_desde": "0001-01-01T00:00:00Z",
                            "vigencia_hasta": null,
                            "installmentdetail": null
                        }
                    },
                    "pago": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "pagostipo_id": 0,
                        "pagoestados_id": 0,
                        "description": "",
                        "first_due_date": "0001-01-01T00:00:00Z",
                        "first_total": 0,
                        "second_due_date": "0001-01-01T00:00:00Z",
                        "payer_name": "",
                        "payer_email": "",
                        "external_reference": "",
                        "metadata": "",
                        "uuid": "",
                        "pdf_url": "",
                        "pagotipo": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "cuentas_id": 0,
                            "pagotipo": "",
                            "back_url_success": "",
                            "back_url_pending": "",
                            "back_url_rejected": "",
                            "included_channels": "",
                            "included_installments": "",
                            "cuenta": {
                                "ID": 0,
                                "CreatedAt": "0001-01-01T00:00:00Z",
                                "UpdatedAt": "0001-01-01T00:00:00Z",
                                "DeletedAt": null,
                                "clientes_id": 0,
                                "cuenta": "",
                                "cbu": "",
                                "cvu": "",
                                "apikey": "",
                                "pagotipos": null,
                                "cuentacomisiones": null
                            }
                        },
                        "pagoestados": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "estado": "",
                            "final": false
                        },
                        "pago_intentos": null,
                        "pagoitems": null
                    }
                }
            ],
            "pagoitems": null
        },
        {
            "ID": 8,
            "CreatedAt": "2021-05-31T13:03:28Z",
            "UpdatedAt": "2021-06-07T11:29:50Z",
            "DeletedAt": null,
            "pagostipo_id": 1,
            "pagoestados_id": 7,
            "description": "Pago de impuesto al sello",
            "first_due_date": "2021-06-10T00:00:00Z",
            "first_total": 760.51,
            "second_due_date": "2021-07-10T00:00:00Z",
            "second_total": 780.55,
            "payer_name": "Nacho Fernandez",
            "payer_email": "fernando.castro@telco.com.ar",
            "external_reference": "155571",
            "metadata": "",
            "uuid": "ce86bbf2d468aw4",
            "pdf_url": "No existe el PDF",
            "pagotipo": {
                "ID": 1,
                "CreatedAt": "2021-05-14T12:49:49Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "cuentas_id": 1,
                "pagotipo": "sellos",
                "back_url_success": "http://www.google.com",
                "back_url_pending": "http://www.infobae.com",
                "back_url_rejected": "http://clarin.com.ar",
                "included_channels": "credit, debit, offline, debin",
                "included_installments": "1,3,6,12",
                "cuenta": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "clientes_id": 0,
                    "cuenta": "",
                    "cbu": "",
                    "cvu": "",
                    "apikey": "",
                    "pagotipos": null,
                    "cuentacomisiones": null
                }
            },
            "pagoestados": {
                "ID": 4,
                "CreatedAt": "2021-06-03T12:39:44Z",
                "UpdatedAt": "2021-06-03T12:39:44Z",
                "DeletedAt": null,
                "estado": "Paid",
                "final": false
            },
			//////////////////
            "pago_intentos": [
                {
                    "ID": 8,
                    "CreatedAt": "2021-06-03T18:30:32Z",
                    "UpdatedAt": "2021-06-30T15:06:41Z",
                    "DeletedAt": null,
                    "pagos_id": 8,
                    "mediopagos_id": 1,
                    "installmentdetails_id": 1,
                    "external_id": "10676500",
                    "paid_at": "2021-06-03T15:30:00Z",
                    "report_at": "2021-06-03T18:30:32Z",
                    "is_available": false,
                    "amount": 760.51,
                    "state_comment": "approved",
                    "barcode": "",
                    "barcode_url": "",
                    "available_at": "2021-06-16T00:00:00Z",
                    "reverted_at": "0001-01-01T00:00:00Z",
                    "holder_name": "Castro",
                    "holder_email": "Castro",
                    "ticket_number": "",
                    "authorization_code": "153031",
                    "card_last_four_digits": "4905",
                    "mediopago": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "channels_id": 0,
                        "adquirientes_id": 0,
                        "installments_id": 0,
                        "mediopago": "",
                        "external_id": "",
                        "longitud_pan": 0,
                        "longitud_cvv": 0,
                        "installmentdetail": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "descripcion": "",
                            "issuer": "",
                            "vigencia_desde": "0001-01-01T00:00:00Z",
                            "vigencia_hasta": null,
                            "installmentdetail": null
                        }
                    },
                    "pago": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "pagostipo_id": 0,
                        "pagoestados_id": 0,
                        "description": "",
                        "first_due_date": "0001-01-01T00:00:00Z",
                        "first_total": 0,
                        "second_due_date": "0001-01-01T00:00:00Z",
                        "payer_name": "",
                        "payer_email": "",
                        "external_reference": "",
                        "metadata": "",
                        "uuid": "",
                        "pdf_url": "",
                        "pagotipo": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "cuentas_id": 0,
                            "pagotipo": "",
                            "back_url_success": "",
                            "back_url_pending": "",
                            "back_url_rejected": "",
                            "included_channels": "",
                            "included_installments": "",
                            "cuenta": {
                                "ID": 0,
                                "CreatedAt": "0001-01-01T00:00:00Z",
                                "UpdatedAt": "0001-01-01T00:00:00Z",
                                "DeletedAt": null,
                                "clientes_id": 0,
                                "cuenta": "",
                                "cbu": "",
                                "cvu": "",
                                "apikey": "",
                                "pagotipos": null,
                                "cuentacomisiones": null
                            }
                        },
                        "pagoestados": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "estado": "",
                            "final": false
                        },
                        "pago_intentos": null,
                        "pagoitems": null
                    }
                },
                {
                    "ID": 7,
                    "CreatedAt": "2021-06-03T18:28:12Z",
                    "UpdatedAt": "2021-06-04T17:58:04Z",
                    "DeletedAt": null,
                    "pagos_id": 8,
                    "mediopagos_id": 2,
                    "installmentdetails_id": 1,
                    "external_id": "0",
                    "paid_at": "0001-01-01T00:00:00Z",
                    "report_at": "2021-06-03T18:28:11Z",
                    "is_available": false,
                    "amount": 760,
                    "state_comment": " {ErrorType:invalid_request_error, ValidationErrors:{Code: ,Param:  ,Status:} Message:,Code:,}",
                    "barcode": "",
                    "barcode_url": "",
                    "available_at": "0001-01-01T00:00:00Z",
                    "reverted_at": "0001-01-01T00:00:00Z",
                    "holder_name": "Ignacio Fernandez",
                    "holder_email": "Ignacio Fernandez",
                    "ticket_number": "",
                    "authorization_code": "",
                    "card_last_four_digits": "0015",
                    "mediopago": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "channels_id": 0,
                        "adquirientes_id": 0,
                        "installments_id": 0,
                        "mediopago": "",
                        "external_id": "",
                        "longitud_pan": 0,
                        "longitud_cvv": 0,
                        "installmentdetail": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "descripcion": "",
                            "issuer": "",
                            "vigencia_desde": "0001-01-01T00:00:00Z",
                            "vigencia_hasta": null,
                            "installmentdetail": null
                        }
                    },
                    "pago": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "pagostipo_id": 0,
                        "pagoestados_id": 0,
                        "description": "",
                        "first_due_date": "0001-01-01T00:00:00Z",
                        "first_total": 0,
                        "second_due_date": "0001-01-01T00:00:00Z",
                        "payer_name": "",
                        "payer_email": "",
                        "external_reference": "",
                        "metadata": "",
                        "uuid": "",
                        "pdf_url": "",
                        "pagotipo": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "cuentas_id": 0,
                            "pagotipo": "",
                            "back_url_success": "",
                            "back_url_pending": "",
                            "back_url_rejected": "",
                            "included_channels": "",
                            "included_installments": "",
                            "cuenta": {
                                "ID": 0,
                                "CreatedAt": "0001-01-01T00:00:00Z",
                                "UpdatedAt": "0001-01-01T00:00:00Z",
                                "DeletedAt": null,
                                "clientes_id": 0,
                                "cuenta": "",
                                "cbu": "",
                                "cvu": "",
                                "apikey": "",
                                "pagotipos": null,
                                "cuentacomisiones": null
                            }
                        },
                        "pagoestados": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "estado": "",
                            "final": false
                        },
                        "pago_intentos": null,
                        "pagoitems": null
                    }
                }
            ],
            "pagoitems": null
        },
        {
            "ID": 11,
            "CreatedAt": "2021-06-03T17:45:13Z",
            "UpdatedAt": "2021-06-07T11:29:50Z",
            "DeletedAt": null,
            "pagostipo_id": 1,
            "pagoestados_id": 7,
            "description": "Pago de impuesto al sello",
            "first_due_date": "2021-06-10T00:00:00Z",
            "first_total": 760.51,
            "second_due_date": "2021-07-10T00:00:00Z",
            "second_total": 780.55,
            "payer_name": "Nicolás de la Cruz",
            "payer_email": "fernando.castro@telco.com.ar",
            "external_reference": "155572",
            "metadata": "",
            "uuid": "d820cfb2db8d8w4",
            "pdf_url": "No existe el PDF",
            "pagotipo": {
                "ID": 1,
                "CreatedAt": "2021-05-14T12:49:49Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "cuentas_id": 1,
                "pagotipo": "sellos",
                "back_url_success": "http://www.google.com",
                "back_url_pending": "http://www.infobae.com",
                "back_url_rejected": "http://clarin.com.ar",
                "included_channels": "credit, debit, offline, debin",
                "included_installments": "1,3,6,12",
                "cuenta": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "clientes_id": 0,
                    "cuenta": "",
                    "cbu": "",
                    "cvu": "",
                    "apikey": "",
                    "pagotipos": null,
                    "cuentacomisiones": null
                }
            },
            "pagoestados": {
                "ID": 4,
                "CreatedAt": "2021-06-03T12:39:44Z",
                "UpdatedAt": "2021-06-03T12:39:44Z",
                "DeletedAt": null,
                "estado": "Paid",
                "final": false
            },
            "pago_intentos": [
                {
                    "ID": 5,
                    "CreatedAt": "2021-06-03T18:24:15Z",
                    "UpdatedAt": "2021-06-30T15:06:41Z",
                    "DeletedAt": null,
                    "pagos_id": 11,
                    "mediopagos_id": 1,
                    "installmentdetails_id": 1,
                    "external_id": "10676452",
                    "paid_at": "2021-06-03T15:24:00Z",
                    "report_at": "2021-06-03T18:24:15Z",
                    "is_available": false,
                    "amount": 760.51,
                    "state_comment": "approved",
                    "barcode": "",
                    "barcode_url": "",
                    "available_at": "2021-06-16T00:00:00Z",
                    "reverted_at": "0001-01-01T00:00:00Z",
                    "holder_name": "Ignacio Fernandez",
                    "holder_email": "Ignacio Fernandez",
                    "ticket_number": "",
                    "authorization_code": "152414",
                    "card_last_four_digits": "4905",
                    "mediopago": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "channels_id": 0,
                        "adquirientes_id": 0,
                        "installments_id": 0,
                        "mediopago": "",
                        "external_id": "",
                        "longitud_pan": 0,
                        "longitud_cvv": 0,
                        "installmentdetail": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "descripcion": "",
                            "issuer": "",
                            "vigencia_desde": "0001-01-01T00:00:00Z",
                            "vigencia_hasta": null,
                            "installmentdetail": null
                        }
                    },
                    "pago": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "pagostipo_id": 0,
                        "pagoestados_id": 0,
                        "description": "",
                        "first_due_date": "0001-01-01T00:00:00Z",
                        "first_total": 0,
                        "second_due_date": "0001-01-01T00:00:00Z",
                        "payer_name": "",
                        "payer_email": "",
                        "external_reference": "",
                        "metadata": "",
                        "uuid": "",
                        "pdf_url": "",
                        "pagotipo": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "cuentas_id": 0,
                            "pagotipo": "",
                            "back_url_success": "",
                            "back_url_pending": "",
                            "back_url_rejected": "",
                            "included_channels": "",
                            "included_installments": "",
                            "cuenta": {
                                "ID": 0,
                                "CreatedAt": "0001-01-01T00:00:00Z",
                                "UpdatedAt": "0001-01-01T00:00:00Z",
                                "DeletedAt": null,
                                "clientes_id": 0,
                                "cuenta": "",
                                "cbu": "",
                                "cvu": "",
                                "apikey": "",
                                "pagotipos": null,
                                "cuentacomisiones": null
                            }
                        },
                        "pagoestados": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "estado": "",
                            "final": false
                        },
                        "pago_intentos": null,
                        "pagoitems": null
                    }
                }
            ],
            "pagoitems": null
        },
        {
            "ID": 12,
            "CreatedAt": "2021-06-03T17:46:50Z",
            "UpdatedAt": "2021-06-07T11:29:50Z",
            "DeletedAt": null,
            "pagostipo_id": 1,
            "pagoestados_id": 3,
            "description": "Pago de impuesto al sello",
            "first_due_date": "2021-06-10T00:00:00Z",
            "first_total": 760.51,
            "second_due_date": "2021-07-10T00:00:00Z",
            "second_total": 780.55,
            "payer_name": "Nicolás de la Cruz",
            "payer_email": "fernando.castro@telco.com.ar",
            "external_reference": "155572",
            "metadata": "",
            "uuid": "77c86bb9d8cf5w4",
            "pdf_url": "No existe el PDF",
            "pagotipo": {
                "ID": 1,
                "CreatedAt": "2021-05-14T12:49:49Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "cuentas_id": 1,
                "pagotipo": "sellos",
                "back_url_success": "http://www.google.com",
                "back_url_pending": "http://www.infobae.com",
                "back_url_rejected": "http://clarin.com.ar",
                "included_channels": "credit, debit, offline, debin",
                "included_installments": "1,3,6,12",
                "cuenta": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "clientes_id": 0,
                    "cuenta": "",
                    "cbu": "",
                    "cvu": "",
                    "apikey": "",
                    "pagotipos": null,
                    "cuentacomisiones": null
                }
            },
            "pagoestados": {
                "ID": 4,
                "CreatedAt": "2021-06-03T12:39:44Z",
                "UpdatedAt": "2021-06-03T12:39:44Z",
                "DeletedAt": null,
                "estado": "Paid",
                "final": false
            },
            "pago_intentos": [
                {
                    "ID": 3,
                    "CreatedAt": "2021-06-03T14:50:26Z",
                    "UpdatedAt": "2021-06-30T15:06:41Z",
                    "DeletedAt": null,
                    "pagos_id": 12,
                    "mediopagos_id": 1,
                    "installmentdetails_id": 1,
                    "external_id": "10676296",
                    "paid_at": "2021-06-03T14:50:00Z",
                    "report_at": "2021-06-03T14:50:13Z",
                    "is_available": false,
                    "amount": 760.51,
                    "state_comment": "approved",
                    "barcode": "",
                    "barcode_url": "",
                    "available_at": "0001-01-01T00:00:00Z",
                    "reverted_at": "2021-06-16T00:00:00Z",
                    "holder_name": "De la Cruz N",
                    "holder_email": "De la Cruz N",
                    "ticket_number": "",
                    "authorization_code": "123",
                    "card_last_four_digits": "4905",
                    "mediopago": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "channels_id": 0,
                        "adquirientes_id": 0,
                        "installments_id": 0,
                        "mediopago": "",
                        "external_id": "",
                        "longitud_pan": 0,
                        "longitud_cvv": 0,
                        "installmentdetail": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "descripcion": "",
                            "issuer": "",
                            "vigencia_desde": "0001-01-01T00:00:00Z",
                            "vigencia_hasta": null,
                            "installmentdetail": null
                        }
                    },
                    "pago": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "pagostipo_id": 0,
                        "pagoestados_id": 0,
                        "description": "",
                        "first_due_date": "0001-01-01T00:00:00Z",
                        "first_total": 0,
                        "second_due_date": "0001-01-01T00:00:00Z",
                        "payer_name": "",
                        "payer_email": "",
                        "external_reference": "",
                        "metadata": "",
                        "uuid": "",
                        "pdf_url": "",
                        "pagotipo": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "cuentas_id": 0,
                            "pagotipo": "",
                            "back_url_success": "",
                            "back_url_pending": "",
                            "back_url_rejected": "",
                            "included_channels": "",
                            "included_installments": "",
                            "cuenta": {
                                "ID": 0,
                                "CreatedAt": "0001-01-01T00:00:00Z",
                                "UpdatedAt": "0001-01-01T00:00:00Z",
                                "DeletedAt": null,
                                "clientes_id": 0,
                                "cuenta": "",
                                "cbu": "",
                                "cvu": "",
                                "apikey": "",
                                "pagotipos": null,
                                "cuentacomisiones": null
                            }
                        },
                        "pagoestados": {
                            "ID": 0,
                            "CreatedAt": "0001-01-01T00:00:00Z",
                            "UpdatedAt": "0001-01-01T00:00:00Z",
                            "DeletedAt": null,
                            "estado": "",
                            "final": false
                        },
                        "pago_intentos": null,
                        "pagoitems": null
                    }
                }
            ],
            "pagoitems": null
        }
    ],


    ESTADOSLOGS
    "lista estado logs": [
        {
            "ID": 0,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "pagos_id": 7,
            "pagoestados_id": 7
        },
        {
            "ID": 0,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "pagos_id": 8,
            "pagoestados_id": 7
        },
        {
            "ID": 0,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "pagos_id": 11,
            "pagoestados_id": 7
        },
        {
            "ID": 0,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "pagos_id": 12,
            "pagoestados_id": 3
        }
    ],




    MOVIMIENTOS
    "lista movimientos": [
        {
            "ID": 0,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "cuentas_id": 1,
            "pagos_id": 7,
            "tipoMovimiento": "D",
            "monto": 660.51,
            "motivo_baja": "",
            "pago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "pagostipo_id": 0,
                "pagoestados_id": 0,
                "description": "",
                "first_due_date": "0001-01-01T00:00:00Z",
                "first_total": 0,
                "second_due_date": "0001-01-01T00:00:00Z",
                "payer_name": "",
                "payer_email": "",
                "external_reference": "",
                "metadata": "",
                "uuid": "",
                "pdf_url": "",
                "pagotipo": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "cuentas_id": 0,
                    "pagotipo": "",
                    "back_url_success": "",
                    "back_url_pending": "",
                    "back_url_rejected": "",
                    "included_channels": "",
                    "included_installments": "",
                    "cuenta": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "clientes_id": 0,
                        "cuenta": "",
                        "cbu": "",
                        "cvu": "",
                        "apikey": "",
                        "pagotipos": null,
                        "cuentacomisiones": null
                    }
                },
                "pagoestados": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "estado": "",
                    "final": false
                },
                "pago_intentos": null,
                "pagoitems": null
            },
            "cuenta": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "clientes_id": 0,
                "cuenta": "",
                "cbu": "",
                "cvu": "",
                "apikey": "",
                "pagotipos": null,
                "cuentacomisiones": null
            },
            "movimiento_comisiones": null
        },
        {
            "ID": 0,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "cuentas_id": 1,
            "pagos_id": 8,
            "tipoMovimiento": "D",
            "monto": 760.51,
            "motivo_baja": "",
            "pago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "pagostipo_id": 0,
                "pagoestados_id": 0,
                "description": "",
                "first_due_date": "0001-01-01T00:00:00Z",
                "first_total": 0,
                "second_due_date": "0001-01-01T00:00:00Z",
                "payer_name": "",
                "payer_email": "",
                "external_reference": "",
                "metadata": "",
                "uuid": "",
                "pdf_url": "",
                "pagotipo": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "cuentas_id": 0,
                    "pagotipo": "",
                    "back_url_success": "",
                    "back_url_pending": "",
                    "back_url_rejected": "",
                    "included_channels": "",
                    "included_installments": "",
                    "cuenta": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "clientes_id": 0,
                        "cuenta": "",
                        "cbu": "",
                        "cvu": "",
                        "apikey": "",
                        "pagotipos": null,
                        "cuentacomisiones": null
                    }
                },
                "pagoestados": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "estado": "",
                    "final": false
                },
                "pago_intentos": null,
                "pagoitems": null
            },
            "cuenta": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "clientes_id": 0,
                "cuenta": "",
                "cbu": "",
                "cvu": "",
                "apikey": "",
                "pagotipos": null,
                "cuentacomisiones": null
            },
            "movimiento_comisiones": null
        },
        {
            "ID": 0,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "cuentas_id": 1,
            "pagos_id": 11,
            "tipoMovimiento": "D",
            "monto": 760.51,
            "motivo_baja": "",
            "pago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "pagostipo_id": 0,
                "pagoestados_id": 0,
                "description": "",
                "first_due_date": "0001-01-01T00:00:00Z",
                "first_total": 0,
                "second_due_date": "0001-01-01T00:00:00Z",
                "payer_name": "",
                "payer_email": "",
                "external_reference": "",
                "metadata": "",
                "uuid": "",
                "pdf_url": "",
                "pagotipo": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "cuentas_id": 0,
                    "pagotipo": "",
                    "back_url_success": "",
                    "back_url_pending": "",
                    "back_url_rejected": "",
                    "included_channels": "",
                    "included_installments": "",
                    "cuenta": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "clientes_id": 0,
                        "cuenta": "",
                        "cbu": "",
                        "cvu": "",
                        "apikey": "",
                        "pagotipos": null,
                        "cuentacomisiones": null
                    }
                },
                "pagoestados": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "estado": "",
                    "final": false
                },
                "pago_intentos": null,
                "pagoitems": null
            },
            "cuenta": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "clientes_id": 0,
                "cuenta": "",
                "cbu": "",
                "cvu": "",
                "apikey": "",
                "pagotipos": null,
                "cuentacomisiones": null
            },
            "movimiento_comisiones": null
        },
        {
            "ID": 0,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "cuentas_id": 1,
            "pagos_id": 12,
            "tipoMovimiento": "C",
            "monto": -760.51,
            "motivo_baja": "",
            "pago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "pagostipo_id": 0,
                "pagoestados_id": 0,
                "description": "",
                "first_due_date": "0001-01-01T00:00:00Z",
                "first_total": 0,
                "second_due_date": "0001-01-01T00:00:00Z",
                "payer_name": "",
                "payer_email": "",
                "external_reference": "",
                "metadata": "",
                "uuid": "",
                "pdf_url": "",
                "pagotipo": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "cuentas_id": 0,
                    "pagotipo": "",
                    "back_url_success": "",
                    "back_url_pending": "",
                    "back_url_rejected": "",
                    "included_channels": "",
                    "included_installments": "",
                    "cuenta": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "clientes_id": 0,
                        "cuenta": "",
                        "cbu": "",
                        "cvu": "",
                        "apikey": "",
                        "pagotipos": null,
                        "cuentacomisiones": null
                    }
                },
                "pagoestados": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "estado": "",
                    "final": false
                },
                "pago_intentos": null,
                "pagoitems": null
            },
            "cuenta": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "clientes_id": 0,
                "cuenta": "",
                "cbu": "",
                "cvu": "",
                "apikey": "",
                "pagotipos": null,
                "cuentacomisiones": null
            },
            "movimiento_comisiones": null
        }
    ],





    PAGOSINTENTOS
    "lista pago intentos": [
        {
            "ID": 6,
            "CreatedAt": "2021-06-03T18:25:25Z",
            "UpdatedAt": "2021-06-30T15:06:41Z",
            "DeletedAt": null,
            "pagos_id": 7,
            "mediopagos_id": 1,
            "installmentdetails_id": 1,
            "external_id": "10676472",
            "paid_at": "2021-06-03T15:25:00Z",
            "report_at": "2021-06-03T18:25:25Z",
            "is_available": false,
            "amount": 660.51,
            "state_comment": "approved",
            "barcode": "",
            "barcode_url": "",
            "available_at": "2021-06-16T00:00:00Z",
            "reverted_at": "0001-01-01T00:00:00Z",
            "holder_name": "Ignacio Fernandez",
            "holder_email": "Ignacio Fernandez",
            "ticket_number": "",
            "authorization_code": "152523",
            "card_last_four_digits": "4905",
            "mediopago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "channels_id": 0,
                "adquirientes_id": 0,
                "installments_id": 0,
                "mediopago": "",
                "external_id": "",
                "longitud_pan": 0,
                "longitud_cvv": 0,
                "installmentdetail": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "descripcion": "",
                    "issuer": "",
                    "vigencia_desde": "0001-01-01T00:00:00Z",
                    "vigencia_hasta": null,
                    "installmentdetail": null
                }
            },
            "pago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "pagostipo_id": 0,
                "pagoestados_id": 0,
                "description": "",
                "first_due_date": "0001-01-01T00:00:00Z",
                "first_total": 0,
                "second_due_date": "0001-01-01T00:00:00Z",
                "payer_name": "",
                "payer_email": "",
                "external_reference": "",
                "metadata": "",
                "uuid": "",
                "pdf_url": "",
                "pagotipo": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "cuentas_id": 0,
                    "pagotipo": "",
                    "back_url_success": "",
                    "back_url_pending": "",
                    "back_url_rejected": "",
                    "included_channels": "",
                    "included_installments": "",
                    "cuenta": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "clientes_id": 0,
                        "cuenta": "",
                        "cbu": "",
                        "cvu": "",
                        "apikey": "",
                        "pagotipos": null,
                        "cuentacomisiones": null
                    }
                },
                "pagoestados": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "estado": "",
                    "final": false
                },
                "pago_intentos": null,
                "pagoitems": null
            }
        },
        {
            "ID": 8,
            "CreatedAt": "2021-06-03T18:30:32Z",
            "UpdatedAt": "2021-06-30T15:06:41Z",
            "DeletedAt": null,
            "pagos_id": 8,
            "mediopagos_id": 1,
            "installmentdetails_id": 1,
            "external_id": "10676500",
            "paid_at": "2021-06-03T15:30:00Z",
            "report_at": "2021-06-03T18:30:32Z",
            "is_available": false,
            "amount": 760.51,
            "state_comment": "approved",
            "barcode": "",
            "barcode_url": "",
            "available_at": "2021-06-16T00:00:00Z",
            "reverted_at": "0001-01-01T00:00:00Z",
            "holder_name": "Castro",
            "holder_email": "Castro",
            "ticket_number": "",
            "authorization_code": "153031",
            "card_last_four_digits": "4905",
            "mediopago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "channels_id": 0,
                "adquirientes_id": 0,
                "installments_id": 0,
                "mediopago": "",
                "external_id": "",
                "longitud_pan": 0,
                "longitud_cvv": 0,
                "installmentdetail": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "descripcion": "",
                    "issuer": "",
                    "vigencia_desde": "0001-01-01T00:00:00Z",
                    "vigencia_hasta": null,
                    "installmentdetail": null
                }
            },
            "pago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "pagostipo_id": 0,
                "pagoestados_id": 0,
                "description": "",
                "first_due_date": "0001-01-01T00:00:00Z",
                "first_total": 0,
                "second_due_date": "0001-01-01T00:00:00Z",
                "payer_name": "",
                "payer_email": "",
                "external_reference": "",
                "metadata": "",
                "uuid": "",
                "pdf_url": "",
                "pagotipo": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "cuentas_id": 0,
                    "pagotipo": "",
                    "back_url_success": "",
                    "back_url_pending": "",
                    "back_url_rejected": "",
                    "included_channels": "",
                    "included_installments": "",
                    "cuenta": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "clientes_id": 0,
                        "cuenta": "",
                        "cbu": "",
                        "cvu": "",
                        "apikey": "",
                        "pagotipos": null,
                        "cuentacomisiones": null
                    }
                },
                "pagoestados": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "estado": "",
                    "final": false
                },
                "pago_intentos": null,
                "pagoitems": null
            }
        },
        {
            "ID": 5,
            "CreatedAt": "2021-06-03T18:24:15Z",
            "UpdatedAt": "2021-06-30T15:06:41Z",
            "DeletedAt": null,
            "pagos_id": 11,
            "mediopagos_id": 1,
            "installmentdetails_id": 1,
            "external_id": "10676452",
            "paid_at": "2021-06-03T15:24:00Z",
            "report_at": "2021-06-03T18:24:15Z",
            "is_available": false,
            "amount": 760.51,
            "state_comment": "approved",
            "barcode": "",
            "barcode_url": "",
            "available_at": "2021-06-16T00:00:00Z",
            "reverted_at": "0001-01-01T00:00:00Z",
            "holder_name": "Ignacio Fernandez",
            "holder_email": "Ignacio Fernandez",
            "ticket_number": "",
            "authorization_code": "152414",
            "card_last_four_digits": "4905",
            "mediopago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "channels_id": 0,
                "adquirientes_id": 0,
                "installments_id": 0,
                "mediopago": "",
                "external_id": "",
                "longitud_pan": 0,
                "longitud_cvv": 0,
                "installmentdetail": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "descripcion": "",
                    "issuer": "",
                    "vigencia_desde": "0001-01-01T00:00:00Z",
                    "vigencia_hasta": null,
                    "installmentdetail": null
                }
            },
            "pago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "pagostipo_id": 0,
                "pagoestados_id": 0,
                "description": "",
                "first_due_date": "0001-01-01T00:00:00Z",
                "first_total": 0,
                "second_due_date": "0001-01-01T00:00:00Z",
                "payer_name": "",
                "payer_email": "",
                "external_reference": "",
                "metadata": "",
                "uuid": "",
                "pdf_url": "",
                "pagotipo": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "cuentas_id": 0,
                    "pagotipo": "",
                    "back_url_success": "",
                    "back_url_pending": "",
                    "back_url_rejected": "",
                    "included_channels": "",
                    "included_installments": "",
                    "cuenta": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "clientes_id": 0,
                        "cuenta": "",
                        "cbu": "",
                        "cvu": "",
                        "apikey": "",
                        "pagotipos": null,
                        "cuentacomisiones": null
                    }
                },
                "pagoestados": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "estado": "",
                    "final": false
                },
                "pago_intentos": null,
                "pagoitems": null
            }
        },
        {
            "ID": 3,
            "CreatedAt": "2021-06-03T14:50:26Z",
            "UpdatedAt": "2021-06-30T15:06:41Z",
            "DeletedAt": null,
            "pagos_id": 12,
            "mediopagos_id": 1,
            "installmentdetails_id": 1,
            "external_id": "10676296",
            "paid_at": "2021-06-03T14:50:00Z",
            "report_at": "2021-06-03T14:50:13Z",
            "is_available": false,
            "amount": 760.51,
            "state_comment": "approved",
            "barcode": "",
            "barcode_url": "",
            "available_at": "0001-01-01T00:00:00Z",
            "reverted_at": "2021-06-16T00:00:00Z",
            "holder_name": "De la Cruz N",
            "holder_email": "De la Cruz N",
            "ticket_number": "",
            "authorization_code": "123",
            "card_last_four_digits": "4905",
            "mediopago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "channels_id": 0,
                "adquirientes_id": 0,
                "installments_id": 0,
                "mediopago": "",
                "external_id": "",
                "longitud_pan": 0,
                "longitud_cvv": 0,
                "installmentdetail": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "descripcion": "",
                    "issuer": "",
                    "vigencia_desde": "0001-01-01T00:00:00Z",
                    "vigencia_hasta": null,
                    "installmentdetail": null
                }
            },
            "pago": {
                "ID": 0,
                "CreatedAt": "0001-01-01T00:00:00Z",
                "UpdatedAt": "0001-01-01T00:00:00Z",
                "DeletedAt": null,
                "pagostipo_id": 0,
                "pagoestados_id": 0,
                "description": "",
                "first_due_date": "0001-01-01T00:00:00Z",
                "first_total": 0,
                "second_due_date": "0001-01-01T00:00:00Z",
                "payer_name": "",
                "payer_email": "",
                "external_reference": "",
                "metadata": "",
                "uuid": "",
                "pdf_url": "",
                "pagotipo": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "cuentas_id": 0,
                    "pagotipo": "",
                    "back_url_success": "",
                    "back_url_pending": "",
                    "back_url_rejected": "",
                    "included_channels": "",
                    "included_installments": "",
                    "cuenta": {
                        "ID": 0,
                        "CreatedAt": "0001-01-01T00:00:00Z",
                        "UpdatedAt": "0001-01-01T00:00:00Z",
                        "DeletedAt": null,
                        "clientes_id": 0,
                        "cuenta": "",
                        "cbu": "",
                        "cvu": "",
                        "apikey": "",
                        "pagotipos": null,
                        "cuentacomisiones": null
                    }
                },
                "pagoestados": {
                    "ID": 0,
                    "CreatedAt": "0001-01-01T00:00:00Z",
                    "UpdatedAt": "0001-01-01T00:00:00Z",
                    "DeletedAt": null,
                    "estado": "",
                    "final": false
                },
                "pago_intentos": null,
                "pagoitems": null
            }
        }
    ]
}
*/
