package administracion

const ERROR_MOVIMIENTO_PAGOS = "no se pudo modificar el valor de los pagos al crear los movimientos"
const ERROR_MOVIMIENTO_PAGOS_INTENTOS = "no se pudo modificar el valor de los pagos intentos al crear los movimientos"
const ERROR_MOVIMIENTO_CIERRE = "no se pudo dar de baja en el cierre de lote al crear los movimientos"
const ERROR_MOVIMIENTO_CREAR = "no se pudo crear los movimientos"
const ERROR_MOVIMIENTO_CREAR_COMISION = "no se pudo crear las comisiones"
const ERROR_CREAR_ESTADO_LOGS = "no se pudo crear los pagos estados logs"
const ERROR_MOVIMIENTO_MATCH = "existen valores para conciliar en el cierre de lotes pero no se encontraron pagos"
const ERROR_REVERSIONES_CREATE = "no se pudo crear las reversiones"
const ERROR_OBTENER_CIERRE_LOTE = "no se pudo obtener los cierre de lotes de Prisma"
const ERROR_OBTENER_PAGOS_INTENTOS = "no se pudo obtener los pagos relacionado con el cierre de lote"
const ERROR_CIERRELOTE_APILINK = "no se pudo dar de baja en el cierre apilink"

//Repository
const ERROR_CARGAR_TOTAL_FILAS = "error al cargar el total de filas de la consulta"
const ERROR_PAGO_ESTADO = "error al cargar el pago estado"
const ERROR_SALDO_CUENTA = "error al cargar el saldo de la cuenta"
const ERROR_CREAR_NOTIFICACION = "no se puedo crear la notificacion"
const ERROR_CREAR_CIERRE_LOTE = "no se pudo crear los cierres de lote"
const ERROR_UPDATE_CIERRE_LOTE = "no se pudo actualizar los cierres de lote"
const ERROR_CREAR_TRANSFERENCIAS = "no se pudo crear las transferencias"
const ERROR_PAGO_ESTADO_EXTERNO = "error al cargar los pagos externos"
const ERROR_CREAR_MOVIMIENTOS = "error al cargar los pagos externos"
const ERROR_BAJAR_MOVIMIENTOS = "error al Bajar los movimientos"
const ERROR_MOVIMIENTO = "error al cargar los movimientos"
const ERROR_CARGAR_TRANSFERENCIA = "error al cargar las transferencias"
const ERROR_MOVIMIENTO_LISTA_DIFERENCIA = "no se encontraron los movimientos seleccionados entre en contacto con el admnistrador del sistema"
const ERROR_PAGO_ESTADO_ID = "el id del pago estado debe ser mayor que cero"
const ERROR_CHANNEL = "error al cargar los canales"
const ERROR_CUENTA_COMISION = "error al cargar cuenta comision"
const ERROR_PAGO_INTENTO = "error al cargar los pagos intentos"
const ERROR_CONFIGURACIONES = "error al cargar las configuraciones"
const ERROR_CREAR_CONFIGURACIONES = "error al crear una configuración"
const ERROR_CHANNEL_ID = "el id del canal debe ser mayor que cero"
const ERROR_CIERRE_PAGO_INTENTO = "no se encontró algún pago intento en el cierre de lote"
const ERROR_LOG = "no se pudo generar el log"
const ERROR_PAGO_LISTA = "la lista de pagos no debe estar vacia"
const ERROR_PAGO_ESTADO_EXTERNO_LISTA = "la lista de pagos externos no debe estar vacia"
const ERROR_ESTADO_PAGO_NO_ENCONTRADO = "no se pudo encontrar el estado de pago"
const ERROR_ESTADO_PAGOS_NO_ENCONTRADO = "no se pudo encontrar estado pagos finales"
const ERROR_PAGO = "error al cargar los pagos"
const ERROR_PAGO_PENDIENTE = "no se encontraron pagos pendientes para procesar"
const ERROR_DEBINES = "	no se encontraron debines pendientes para procesar"
const ERROR_LISTA_CIERRE_LOTE = "la lista de cierres de lote no debe estar vacia"
const ERROR_LISTA_CIERRE_LOTE_RAPIPAGO = "la lista de cierre lote rapipago no coinicide con la lista de pagos intentos"
const ERROR_IMPORTE_TRANSFERENCIA = "el importe informado es incorrecto"
const ERROR_SALDO_CUENTA_INSUFICIENTE = "el saldo de la cuenta es insuficiente"
const ERROR_LISTA_CIERRE_LOTE_VACIA = "lista cierre lote vacia"
const ERROR_REQUERIMIENTO_ID = "el formato del requerimientoId es invalido"
const ERROR_CUENTA_ID = "el parametro cuentaId no debe ser 0"
const ERROR_USER_ID = "el parametro userId no debe ser 0"
const ERROR_CONVERSION = "error de conversión de datos"
const ERROR_ESCRIBIR_ARCHIVO = "no se pudo escribir los datos en el archivo"
const ERROR_UPDATE_PAGO = "no se pudo modificar los pagos"
const ERROR_UPDATE_TRANSFERENCIAS = "no se pudo modificar las transferencias, error al conciliar datos con banco"
const ERROR_IMPUESTO = "error al cargar los impuestos"
const ERROR_CHANNEL_ARANCEL = "error al cargar canales arancel"
const ERROR_CIERRE_LOTE = "error al cargar cierre lotes"
const ERROR_PRISMA_PX = "error al cargar prisma px"
const ERROR_PRISMA_MX = "error al cargar prisma Mx"
const ERROR_IMPORTE_ENVIADO = "error de importe, el valor no puede ser negativo"

//CLIENTES
const ERROR_CREAR_CLIENTE = "error al crear clientes"
const ERROR_CLIENTE_REGISTRADO = "ya existe un cliente con el mismo numero de cuit"
const ERROR_CREAR_RUBRO = "error al crear rubros"
const ERROR_CREAR_PAGO_TIPO = "error al crear pago tipo"
const ERROR_CREAR_CHANNEL = "error al crear channel"
const ERROR_CREAR_CUENTA_COMISION = "error al crear cuenta comision"
const ERROR_CARGAR_CLIENTE = "error al cargar el cliente"
const ERROR_CARGAR_CUENTA = "error al cargar el cuenta"
const ERROR_CARGAR_RUBROS = "error al cargar rubros"
const ERROR_CARGAR_PAGO_TIPO = "error al cargar pago tipo"
const ERROR_BAJAR_CLIENTE = "error al dar de baja en cliente"
const ERROR_BAJAR_CUENTA = "error al dar de baja en cuenta"
const ERROR_BAJAR_CUENTA_COMISION = "error al dar de baja en cuenta comision"
const ERROR_BAJAR_CHANNEL = "error al dar de baja en channel"
const ERROR_BAJAR_PAGO_TIPO = "error al dar de baja en pago tipo"
const ERROR_BAJAR_RUBRO = "error al dar de baja en cliente"
const ERROR_MODIFICAR_CLIENTE = "error al modificar el cliente"
const ERROR_MODIFICAR_CUENTA = "error al modificar el cuenta"
const ERROR_MODIFICAR_APIKEY = "error al modificar apikey"
const ERROR_MODIFICAR_RUBRO = "error al modificar el rubro"
const ERROR_MODIFICAR_PAGO_TIPO = "error al modificar pago tipo"
const ERROR_MODIFICAR_CUENTA_COMISION = "error al modificar cuenta comision"
const ERROR_MODIFICAR_CHANNEL = "error al modificar channel"
const ERROR_CBU_REGISTRADO = "el cbu ya esta registrado en el sistema"
const ERROR_CVU_REGISTRADO = "el cvu ya esta registrado en el sistema"
const ERROR_CREAR_IMPUESTO = "error al crear impuesto"

//GENERAL
const RESULTADO_NO_ENCONTRADO = "no se encontraron resultados para la busqueda"
const ERROR_ID = "el id es invalido"

const ERROR_SOLICITUD_CUENTA = "la solicitud no pudo ser enviada en este momento. Intente nuevamente mas tarde"
const ERROR_ENVIAR_EMAIL_TERMINOS_CONDICIONES = "no pudimos actualizar los terminos y condiciones. Intente nuevamente mas tarde"

const ERROR_CREAR = "no se pudo guardar en la base de datos tipo "

// administracion
const ERROR_LEER_ARCHIVO = "no se pudo leer el archivo"
const ERROR_CONVERSION_DATO = "error de conversión de datos"
const ERROR_CONSULTA_INSTALLMENT = "error al consultar plan de cuota"
const ERROR_ACTUALIZAR_INSTALLMENT = "error al actualizar plan de cuota"
const ERROR_CREAR_INSTALLMENT = "error al crear plan de cuota"
const ERROR_CREAR_INSTALLMENT_DETAILS = "error al crear detalle plan de cuota"

const ERROR_RAPIPAGO = "error al cargar los movimientos de rapipago"

const ERROR_CONSULTAR_PLANESCUOTAS = "erro al obtener los planes de cuotas"

//cuenta
const ERROR_CONSULTAR_CUENTA = "no se pudo realizar la consulta"
const ERROR_CUENTA_VACIA = "no existe cuenta"

const ERROR_OBTENER_PAGOS_DISPUTA = "no se pudo obtener información de los pagos en disputa"

const ERROR_TRANSFERENCIA_AUTOMATICA = "la transferencia automatica no pudo ser enviada en este momento"
const ERROR_TRANSFERENCIA_COMISIONES = "la transferencia de comisiones no puede realizarse: error al consultar tabla transferenciacomisiones"
const ERROR_VACIO_PAGOS_DISPUTA = "lista de pagos en disputa vacia"

// Solicitud de Cuenta Repository
const ERROR_CREAR_SOLICITUD_CUENTA = "error al intentar guardar la solicitud de nueva cuenta"

// CLRapipago y apilink
const ACTUALIZAR_ESTADOS_CL_RAPIPAGO = "no se puedo actualizar los estados de los pagos/clrapipago"
const ACTUALIZAR_ESTADOS_CL_APILINK = "no se puedo actualizar los estados de los pagos/clapilink"
const ERROR_CREAR_CLAPILINK = "no se pudo crear los registros en apilinkcierrelote"

const ERROR_LISTA_PAGOS_INTENTOS = "la lista de pagos intentos para la generacion de movimientos temporales no coinciden"

// CLMultipagos y apilink
const ACTUALIZAR_ESTADOS_CL_MULTIPAGOS = "no se puedo actualizar los estados de los pagos/clmultipagos"

// RETENCIONES IMPOSITIVAS
const ERROR_CARGAR_RETENCIONES = "al cargar retenciones desde el repositorio"
const ERROR_CARGAR_CLIENTE_RETENCIONES = "al cargar retenciones de un cliente desde el repositorio"
const ERROR_CREAR_CLIENTE_RETENCION = "al crear la retenciones de un cliente desde el repositorio"
const ERROR_OBTENER_CLIENTE_RETENCION = "al obtener y asignar la retenciones y el cliente desde el repositorio"
const ERROR_DB_ACCESS = "al intentar acceder a la base de datos desde el repositorio"
const ERROR_CALCULAR_CLIENTE_RETENCIONES = "al calcular retenciones de un cliente desde el repositorio"
const ERROR_CARGAR_GRAVAMENES = "al obtener gravamenes desde el repositorio"
const ERROR_CARGAR_CONDICIONES = "al obtener codiciones impositivas desde el repositorio"
const ERROR_CREAR_RETENCION = "al crear la retencion desde el repositorio"
const ERROR_DELETE_RETENCION = "al intentar eliminar la retencion del cliente desde el repositorio"
const ERROR_UPDATE_RETENCION = "al intentar modificar la retencion desde el repositorio"
const ERROR_UPDATE_COMPROBANTE = "al intentar modificar el comprobante desde el repositorio"
const ERROR_CREAR_CONDICION = "al crear la condicion impositiva desde el repositorio"
const ERROR_UPDATE_CONDICION = "al intentar modificar la condicion desde el repositorio"
const ERROR_GET_CLIENTE_RETENCION = "al intentar encontrar la retencion especifica de un cliente desde el repositorio"
const ERROR_GET_MOVIMIENTOS_RETENCION = "al intentar obtener ids de movimientos-retenciones desde el repositorio"
const ERROR_GET_TOTAL_AMOUNT = "al intentar obtener el total del monto sujeto a retencion desde el repositorio"
const ERROR_RETENCIONES_DEVOLVER = "al intentar obtener retenciones no aplicables desde el repositorio"
const ERROR_GET_COMPROBANTES = "al intentar obtener comprobantes de retenciones desde el repositorio"
const ERROR_CREAR_CERTIFICACION = "al crear la certificacion impositiva desde el repositorio"
